[package]
name = "day21"
version = "0.1.0"
edition = "2021"

[dependencies]
bimap = "0.6"
once_cell = "1.20.2"
petgraph = "0.7"

[dev-dependencies]
rstest = "0.23.0"
assert_cmd = "2.0"

[[bin]]
name = "day21"
path = "src/main.rs"